version: '3'
services:
  gitlab:
    restart: always
    image: gitlab/gitlab-ce:14.5.0-ce.0
    container_name: gitlab
    hostname: 'gitlab.rinlink.jp'
    ports:
      - "8929:8929"
      - "2224:22"
    entrypoint: |
      bash -c 'sed -i "s/MIN_CHARS_FOR_PARTIAL_MATCHING = 3/MIN_CHARS_FOR_PARTIAL_MATCHING = 1/g" /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/sql/pattern.rb && /assets/wrapper'
    volumes:
      - '$PWD/config:/etc/gitlab'
      - '$PWD/logs:/var/log/gitlab'
      - '$PWD/data:/var/opt/gitlab'
      - '/etc/localtime:/etc/localtime:rw'
      - '$PWD/embedded-logs:/opt/gitlab/embedded/logs/'
    environment:
      DEBUG: 'false'
      GITLAB_PORT: 8929
      GITLAB_SSH_PORT: 22
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.rinlink.jp'
        nginx['client_max_body_size'] = '512m'
        nginx['listen_port'] = 8929
        nginx['enable'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['time_zone'] = 'Asia/Tokyo'
        gitlab_rails['gitlab_signup_enabled'] = false
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['ldap_servers'] = YAML.load <<-'EOS'
          main:
            label: 'RINRIN.NET AD'
            host: 'rinrin.net'
            port: 3268
            uid: 'SamAccountName'
            encryption: 'plain'
            verify_certificates: true
            bind_dn: 'cn=wei,ou=AdminUser,dc=rinrin,dc=net'
            password: 'rinriN@rinrinnet'
            block_auto_created_users: false
            allow_username_or_email_login: true
            base: 'cn=lin,ou=AdminUser,dc=rinrin,dc=net'
            user_filter: ''
        EOS
        gitlab_rails['ldap_block_auto_created_users'] = false
        prometheus['enable'] = false
    dns:
      - 10.0.1.200

